version: 0.2
env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: aws_access_key:AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: aws_secret_access_key:AWS_SECRET_ACCESS_KEY
    TF_VAR_customer_license_id: customer_license_id:TF_VAR_customer_license_id
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan